### ISSUE TITLE
Available resources do not appear in application 'Resources' screen

### ISSUE THREAD

**Issue by atsag** [eu-nebulous/gui-controller#24]
While registering a new application, I could not select the resources that were available to me, as the screen was empty and no choice could be made. A screenshot is attached.
![image](https://github.com/user-attachments/assets/c8edadc0-2af1-462d-babf-390b1049f68e)
The bug appears to influence in particular our user account

**Comment by robert-sanfeliu** [comment]
@atsag I have experienced the same problem after we restored a a backup of the DB a couple of weeks ago. In my case, the issue was due to some preexisitng cloud providers not having the "platform" set. The solution was to remove those that didn't had platform.

In the list of cloud providers you shouldn't see any without platform:
![image](https://github.com/user-attachments/assets/305690a0-9556-4753-8e8b-f8e2d5d35d55)

**Comment by atsag** [comment]
Right, this is the way to solve the issue - closing the bug.
